### ISSUE TITLE
manque des taches dans l'excercice PHP

### ISSUE THREAD

**Issue by salv236** [becodeorg/BXLCentral#11]
- il manque une exercice pour le boucle do/while
 - pour les fonction ils manque pass by reference et pass by value (important un developpeur m'a communique qu'il a eu un question sur ce sujet.

**Comment by pixeline** [comment]
je ne comprends pas ton second point. Tu peux reformuler, ou donner un exemple?

**Comment by pixeline** [comment]
pour le do/while, je la trouve peu intuitive, et donc ne l'utilise jamais. Libre à toi de voir par toi-même, on vous met sur les rails, mais c'est à vous d'apprendre ce que vous voulez apprendre. 
http://php.net/manual/en/control-structures.do.while.php
